name: mysterylane
description: "MysteryLane"
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.12.3
  geolocator: ^14.0.3
  http: ^1.6.0
  supabase_flutter: ^2.17.2
  image_picker: ^1.1.2
  intl_phone_field: ^3.2.0
  intl_phone_number_input: ^0.7.5

  google_maps_apis: ^5.1.0
  flutter_polyline_points: ^2.0.0
  pdf: ^3.10.4
  printing: ^5.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - env/dev.json
